language: java
jdk:
  - openjdk11

branches:
  only:
    - develope
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

notifications:
  slack: w1647304024-c1w704883:d3gvjHoW3psmzQcbZZqfwPJk